export enum LISTING_TYPE {
  SALE = "SALE",
  RENT = "RENT",
}

export enum PROPERTY_TYPE {
  DETACHED = "DETACHED",
  SEMI = "SEMI",
  SEMI_DETACHED = "SEMI_DETACHED",
  TERRACED = "TERRACED",
  BUNGLOW = "BUNGLOW",
  APARTMENT = "APARTMENT",
  COUNTRY_HOUSE = "COUNTRY_HOUSE",
  FLAT = "FLAT",
  PARK_HOME = "PARK_HOME",
  VILLA = "VILLA",
}

export enum TENURE {
  FREEHOLD = "FREEHOLD",
  LEASEHOLD = "LEASEHOLD",
  SHARE_OF_FREEHOLD = "SHARE_OF_FREEHOLD",
}

export enum COUNCIL_TAX_BAND {
  A = "A",
  B = "B",
  C = "C",
  D = "D",
  E = "E",
  F = "F",
  G = "G",
  H = "H",
}

export enum FEATURES {
  GARDEN = "GARDEN",
  PARKING = "PARKING",
  NEW_BUILD = "NEW_BUILD",
  CHAIN_FEE = "CHAIN_FEE",
  SWIMMING_POOL = "SWIMMING_POOL",
  GYM = "GYM",
  CONCIERGE = "CONCIERGE",
  BALCONY = "BALCONY",
  TERRACE = "TERRACE",
  LIFT = "LIFT",
  FITTED_KITCHEN = "FITTED_KITCHEN",
  UNDER_FLOOR_HEATING = "UNDER_FLOOR_HEATING",
  SOLAR_PANELS = "SOLAR_PANELS",
  OFF_STREET_PARKING = "OFF_STREET_PARKING",
  DRIVEWAY = "DRIVEWAY",
  ALARM_SYSTEM = "ALARM_SYSTEM",
}

export enum LISTING_STATUS {
  DRAFT = "DRAFT",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  PUBLISHED = "PUBLISHED",
  REJECTED = "REJECTED",
  SOLD = "SOLD",
}
