export enum LOTTERY_STATUS {
  DRAFT = "DRAFT",
  SCHEDULED = "SCHEDULED",
  ACTIVE = "ACTIVE",
  ENDED = "ENDED",
  DRAWN = "DRAWN",
}

export enum LOTTERY_MODE {
  INSTANT = "INSTANT",
  SCHEDULE = "SCHEDULE",
  DRAFT = "DRAFT",
}
