export enum PLATFORM_PLAN_DURATION {
    MONTHLY = "MONTHLY",
    QUARTERLY = "QUARTERLY",
    HALF_YEARLY = "HALF_YEARLY",
    YEARLY = "YEARLY",
}


export enum PLAN_TIER {
    TRIAL = "TRIAL",
    STARTER = "STARTER",
    PROFESSIONAL = "PROFESSIONAL",
    PREMIUM = "PREMIUM",
}

export enum PLAN_STATUS {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
}

